import { test, expect } from '@playwright/test';

test('owner activates an empty workspace, client registers, coach assigns a workout, and client completes it', async ({ page, browser }) => {
  test.setTimeout(90_000);
  const failures = []; page.on('pageerror', error => failures.push(error.message));
  await page.goto('/#setup=' + 'd'.repeat(64));
  await expect(page).toHaveTitle(/Train with me/);
  await page.getByLabel('Full name').fill('Private Owner');
  await page.getByLabel('Email address').fill('owner-browser@example.com');
  await page.getByLabel(/^Choose a password/).fill('OwnerBrowser123!');
  await page.getByLabel('Confirm password', { exact: true }).fill('OwnerBrowser123!');
  await page.getByRole('button', { name: 'Create my workspace', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Good .*Private/ })).toBeVisible();
  await expect(page.getByText('Demo workspace', { exact: true })).toHaveCount(0);
  await page.getByRole('navigation').getByRole('button', { name: 'Schedule', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Schedule session', exact: true })).toBeDisabled();
  await expect(page.getByText('Sessions need a client.', { exact: false })).toBeVisible();
  await page.getByRole('navigation').getByRole('button', { name: 'Workout plans', exact: true }).click();
  await page.locator('.page-heading').getByRole('button', { name: 'Build a workout', exact: true }).click();
  let libraryDialog = page.getByRole('dialog');
  await expect(libraryDialog.getByRole('combobox', { name: 'Client', exact: true })).toHaveValue('');
  await expect(libraryDialog.getByLabel('Workout date')).toHaveCount(0);
  await libraryDialog.getByLabel('Workout name').fill('First registered workout');
  await libraryDialog.getByRole('button', { name: /Bodyweight squat/ }).click();
  await libraryDialog.getByLabel('Bodyweight squat Rest (sec)', { exact: true }).fill('75');
  await libraryDialog.getByLabel('Coaching note', { exact: true }).fill('Controlled tempo');
  await libraryDialog.getByLabel('Workout notes').fill('Warm up before training');
  await libraryDialog.getByRole('button', { name: 'Save workout', exact: true }).click();
  await expect(page.locator('.workout-template-library').getByRole('heading', { name: 'First registered workout', exact: true })).toBeVisible();
  await page.getByRole('button', { name: /^Weekly lineups/ }).click();
  await page.getByRole('button', { name: 'Build a weekly lineup', exact: true }).first().click();
  await page.getByRole('dialog').getByLabel('Weekly lineup name').fill('Private three-day lineup');
  for (const day of ['Monday', 'Wednesday', 'Friday']) await page.getByRole('dialog').getByLabel(`${day} routine`, { exact: true }).selectOption({ label: 'First registered workout' });
  await page.getByRole('dialog').getByRole('button', { name: 'Save weekly lineup', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeHidden();
  await page.getByRole('button', { name: 'Assign to client', exact: true }).click();
  await expect(page.getByRole('dialog')).toContainText('Add or invite a client');
  await page.getByRole('dialog').getByRole('button', { name: 'Close', exact: true }).click();
  await page.reload();
  const coachResult = await page.request.post('/api/users', { data: { name: 'Independent Coach', email: 'independent-coach@example.com', password: 'IndependentCoach123!', role: 'coach' } });
  expect(coachResult.status()).toBe(201);
  const coachContext = await browser.newContext({ baseURL: new URL(page.url()).origin, timezoneId: 'UTC', viewport: { width: 390, height: 844 } });
  try {
    const coachPage = await coachContext.newPage(); coachPage.on('pageerror', error => failures.push(error.message));
    await coachPage.goto('/');
    await coachPage.getByLabel('Email address').fill('independent-coach@example.com');
    await coachPage.getByLabel('Password', { exact: true }).fill('IndependentCoach123!');
    await coachPage.getByRole('button', { name: 'Sign in', exact: true }).click();
    await expect(coachPage.getByRole('heading', { name: /Good .*Independent/ })).toBeVisible();
    await coachPage.getByRole('button', { name: 'Open menu', exact: true }).click();
    await coachPage.getByRole('navigation').getByRole('button', { name: 'Workout plans', exact: true }).click();
    await coachPage.locator('.page-heading').getByRole('button', { name: 'Build a workout', exact: true }).click();
    const coachDialog = coachPage.getByRole('dialog');
    await coachDialog.getByLabel('Workout name').fill('Coach library without clients');
    await coachDialog.getByRole('button', { name: /Bodyweight squat/ }).click();
    await coachDialog.getByRole('button', { name: 'Save workout', exact: true }).click();
    await expect(coachPage.getByRole('heading', { name: 'Coach library without clients', exact: true })).toBeVisible();
    await expect.poll(() => coachPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await expect(coachPage.getByRole('heading', { name: 'First registered workout', exact: true })).toHaveCount(0);
  } finally { await coachContext.close(); }
  await page.getByRole('navigation').getByRole('button', { name: /^My clients/ }).click();
  await expect(page.getByText('Your coaching journey starts here')).toBeVisible();
  await page.getByRole('button', { name: 'Invite client', exact: true }).click();
  let dialog = page.getByRole('dialog');
  await dialog.getByLabel('Full name').fill('Registered Client');
  await dialog.getByLabel('Email address').fill('registered-browser@example.com');
  await dialog.getByLabel('Training goal').fill('Improve strength');
  await dialog.getByRole('button', { name: 'Create signup link', exact: true }).click();
  const link = await dialog.getByLabel('Signup link', { exact: true }).inputValue();
  await dialog.getByRole('button', { name: 'Done', exact: true }).click();
  await expect(page.getByText('Pending', { exact: true })).toBeVisible();

  const context = await browser.newContext({ baseURL: new URL(page.url()).origin, timezoneId: 'UTC', viewport: { width: 390, height: 844 } });
  try {
    const client = await context.newPage(); client.on('pageerror', error => failures.push(error.message));
    await client.goto(link);
    await expect(client.getByRole('heading', { name: 'Create your client account', exact: true })).toBeVisible();
    await expect(client.getByLabel('Email address')).toHaveValue('registered-browser@example.com');
    await expect(client.getByLabel('Email address')).toHaveAttribute('readonly', '');
    await client.getByLabel(/^Choose a password/).fill('RegisteredClient123!');
    await client.getByLabel('Confirm password', { exact: true }).fill('RegisteredClient123!');
    await client.getByRole('button', { name: 'Create my account', exact: true }).click();
    await expect(client.getByRole('heading', { name: /Good .*Registered/ })).toBeVisible();
    await expect(client.getByRole('button', { name: 'Sign out', exact: true })).toBeVisible();
    await expect.poll(() => client.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.reload();
    await page.getByRole('navigation').getByRole('button', { name: /^My clients/ }).click();
    await expect(page.getByRole('heading', { name: 'Registered Client', exact: true })).toBeVisible();
    await page.getByRole('navigation').getByRole('button', { name: 'Workout plans', exact: true }).click();
    await page.getByRole('button', { name: /^Daily routines/ }).click();
    const templateCard = page.locator('article').filter({ has: page.getByRole('heading', { name: 'First registered workout', exact: true }) });
    await templateCard.getByRole('button', { name: 'Copy to client', exact: true }).click();
    dialog = page.getByRole('dialog');
    await dialog.getByLabel('Workout date').fill(new Date().toISOString().slice(0, 10));
    await dialog.getByRole('button', { name: 'Copy workout', exact: true }).click();
    await expect(dialog).toBeHidden();
    await page.getByRole('button', { name: /^Daily routines/ }).click();
    await templateCard.getByRole('button', { name: 'Edit workout', exact: true }).click();
    await page.getByRole('dialog').getByLabel('Bodyweight squat Sets', { exact: true }).fill('5');
    await page.getByRole('dialog').getByRole('button', { name: 'Save changes', exact: true }).click();
    await expect(page.getByRole('dialog')).toBeHidden();
    await client.reload();
    await client.getByRole('button', { name: 'Open menu', exact: true }).click();
    await client.getByRole('navigation').getByRole('button', { name: 'My workouts', exact: true }).click();
    const card = client.locator('article').filter({ has: client.getByRole('heading', { name: 'First registered workout', exact: true }) });
    await card.getByRole('button', { name: 'Log workout', exact: true }).click();
    await expect(client.getByRole('dialog').getByText('Planned: 3 × 10 reps · Bodyweight', { exact: true })).toBeVisible();
    await expect(client.getByRole('dialog').getByText('Controlled tempo', { exact: true })).toBeVisible();
    await client.getByRole('dialog').getByRole('button', { name: 'Mark complete', exact: true }).click();
    await expect(card.getByText('Completed', { exact: true })).toBeVisible();
    await client.getByRole('button', { name: 'Sign out', exact: true }).click();
    await expect(client.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible();
    await client.getByLabel('Email address').fill('registered-browser@example.com');
    await client.getByLabel('Password', { exact: true }).fill('RegisteredClient123!');
    await client.getByRole('button', { name: 'Sign in', exact: true }).click();
    await expect(client.getByRole('heading', { name: /Good .*Registered/ })).toBeVisible();
    await client.goto(link);
    await expect(client.getByRole('alert')).toContainText('no longer available');
    await client.getByRole('button', { name: 'Back to sign in', exact: true }).click();
    await expect(client.getByRole('heading', { name: /Good .*Registered/ })).toBeVisible();
    await page.reload();
    await page.getByRole('navigation').getByRole('button', { name: 'Workout plans', exact: true }).click();
    await expect(page.locator('article').filter({ has: page.getByRole('heading', { name: 'First registered workout', exact: true }) }).getByText('Completed', { exact: true })).toBeVisible();
    const completed = page.locator('article').filter({ has: page.getByRole('heading', { name: 'First registered workout', exact: true }) });
    await completed.getByRole('button', { name: 'Copy to client', exact: true }).click();
    await page.getByRole('dialog').getByLabel('Workout name').fill('Repeat registered workout');
    await page.getByRole('dialog').getByRole('button', { name: 'Copy workout', exact: true }).click();
    await expect(page.getByRole('dialog')).toBeHidden();
    await page.getByRole('navigation').getByRole('button', { name: 'Progress & assessments', exact: true }).click();
    await page.getByRole('button', { name: 'Body fat %', exact: true }).click();
    await expect(page.getByRole('dialog').getByLabel('Unit')).toHaveValue('%');
    await page.getByRole('dialog').getByLabel('Body fat (%)', { exact: true }).fill('24.5');
    await page.getByRole('dialog').getByLabel(/^Notes/).fill('Body composition scale');
    await page.getByRole('dialog').getByRole('button', { name: 'Save assessment', exact: true }).click();
    await expect(page.getByRole('dialog')).toBeHidden();
    await client.reload();
    await client.getByRole('button', { name: 'Open menu', exact: true }).click();
    await client.getByRole('navigation').getByRole('button', { name: 'Progress & assessments', exact: true }).click();
    await expect(client.locator('.pg-stat').filter({ hasText: 'Body fat percentage' }).getByText('24.5', { exact: true })).toBeVisible();
    await expect(client.getByRole('heading', { name: 'Body fat percentage', exact: true })).toBeVisible();
    await expect.poll(() => client.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    expect(failures).toEqual([]);
  } finally { await context.close(); }
});
