import { test, expect } from '@playwright/test';

test('owner activates an empty workspace, client registers, coach assigns a workout, and client completes it', async ({ page, browser }) => {
  const failures = []; page.on('pageerror', error => failures.push(error.message));
  await page.goto('/#setup=' + 'd'.repeat(64));
  await expect(page).toHaveTitle(/Train with me/);
  await page.getByLabel('Full name').fill('Private Owner');
  await page.getByLabel('Email address').fill('owner-browser@example.com');
  await page.getByLabel(/^Choose a password/).fill('OwnerBrowser123!');
  await page.getByLabel('Confirm password', { exact: true }).fill('OwnerBrowser123!');
  await page.getByRole('button', { name: 'Create my workspace', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Good .*Private/ })).toBeVisible();
  await expect(page.getByText('Demo workspace', { exact: true })).toHaveCount(0);
  await page.getByRole('navigation').getByRole('button', { name: /^My clients/ }).click();
  await expect(page.getByText('Your coaching journey starts here')).toBeVisible();
  await page.getByRole('button', { name: 'Invite client', exact: true }).click();
  let dialog = page.getByRole('dialog');
  await dialog.getByLabel('Full name').fill('Registered Client');
  await dialog.getByLabel('Email address').fill('registered-browser@example.com');
  await dialog.getByLabel('Training goal').fill('Improve strength');
  await dialog.getByRole('button', { name: 'Create signup link', exact: true }).click();
  const link = await dialog.getByLabel('Signup link', { exact: true }).inputValue();
  await dialog.getByRole('button', { name: 'Done', exact: true }).click();
  await expect(page.getByText('Pending', { exact: true })).toBeVisible();

  const context = await browser.newContext({ baseURL: new URL(page.url()).origin, timezoneId: 'UTC', viewport: { width: 390, height: 844 } });
  try {
    const client = await context.newPage(); client.on('pageerror', error => failures.push(error.message));
    await client.goto(link);
    await expect(client.getByRole('heading', { name: 'Create your client account', exact: true })).toBeVisible();
    await expect(client.getByLabel('Email address')).toHaveValue('registered-browser@example.com');
    await expect(client.getByLabel('Email address')).toHaveAttribute('readonly', '');
    await client.getByLabel(/^Choose a password/).fill('RegisteredClient123!');
    await client.getByLabel('Confirm password', { exact: true }).fill('RegisteredClient123!');
    await client.getByRole('button', { name: 'Create my account', exact: true }).click();
    await expect(client.getByRole('heading', { name: /Good .*Registered/ })).toBeVisible();
    await expect(client.getByRole('button', { name: 'Sign out', exact: true })).toBeVisible();
    await expect.poll(() => client.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.reload();
    await page.getByRole('navigation').getByRole('button', { name: /^My clients/ }).click();
    await expect(page.getByRole('heading', { name: 'Registered Client', exact: true })).toBeVisible();
    await page.getByRole('navigation').getByRole('button', { name: 'Workout plans', exact: true }).click();
    await page.locator('.page-heading').getByRole('button', { name: 'Build a workout', exact: true }).click();
    dialog = page.getByRole('dialog');
    await dialog.getByLabel('Workout date').fill(new Date().toISOString().slice(0, 10));
    await dialog.getByLabel('Workout name').fill('First registered workout');
    await dialog.getByRole('button', { name: /Bodyweight squat/ }).click();
    await dialog.getByRole('button', { name: 'Save workout', exact: true }).click();
    await expect(dialog).toBeHidden();
    await client.reload();
    await client.getByRole('button', { name: 'Open menu', exact: true }).click();
    await client.getByRole('navigation').getByRole('button', { name: 'My workouts', exact: true }).click();
    const card = client.locator('article').filter({ has: client.getByRole('heading', { name: 'First registered workout', exact: true }) });
    await card.getByRole('button', { name: 'Log workout', exact: true }).click();
    await client.getByRole('dialog').getByRole('button', { name: 'Mark complete', exact: true }).click();
    await expect(card.getByText('Completed', { exact: true })).toBeVisible();
    await client.getByRole('button', { name: 'Sign out', exact: true }).click();
    await expect(client.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible();
    await client.getByLabel('Email address').fill('registered-browser@example.com');
    await client.getByLabel('Password', { exact: true }).fill('RegisteredClient123!');
    await client.getByRole('button', { name: 'Sign in', exact: true }).click();
    await expect(client.getByRole('heading', { name: /Good .*Registered/ })).toBeVisible();
    await client.goto(link);
    await expect(client.getByRole('alert')).toContainText('no longer available');
    await client.getByRole('button', { name: 'Back to sign in', exact: true }).click();
    await expect(client.getByRole('heading', { name: /Good .*Registered/ })).toBeVisible();
    await page.reload();
    await page.getByRole('navigation').getByRole('button', { name: 'Workout plans', exact: true }).click();
    await expect(page.locator('article').filter({ has: page.getByRole('heading', { name: 'First registered workout', exact: true }) }).getByText('Completed', { exact: true })).toBeVisible();
    expect(failures).toEqual([]);
  } finally { await context.close(); }
});
