import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { test, expect } from '@playwright/test';
const login=async(page,role='coach')=>{if(role==='coach'){await page.request.post('/api/auth/login',{data:{email:'admin@form.fit',password:'FormDemo123!'}});await page.request.patch('/api/users/user-coach',{data:{password:'FormDemo123!'}});await page.request.post('/api/auth/logout');}await page.goto('/');await page.getByRole('button',{name:role==='coach'?'Coach Plan & guide':role==='admin'?'Admin Curate the library':'Client Train & track'}).click();await expect(page.getByRole('navigation',{name:'Main navigation'})).toBeVisible();};
const nav=(page,name)=>page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name,exact:true}).click();
async function noOverflow(page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();}
test('coach edits sample, orders poses and sections by keyboard and drag, saves, previews, publishes and assigns',async({page})=>{
 await login(page);await nav(page,'Yoga');await expect(page.getByText('12 flows ·', {exact:false})).toBeVisible();
 const card=page.locator('.yoga-flow-card').filter({has:page.getByRole('heading',{name:'Heart Opening & Gratitude',exact:true})});await expect(card).toContainText('45 min');await card.getByRole('button',{name:'Duplicate',exact:true}).click();
 await expect(page.getByText('All changes saved',{exact:false})).toBeVisible();await page.getByRole('textbox',{name:'Class title',exact:true}).fill('Browser yoga gratitude');
 await expect(page.getByText('Total Class Duration: 45 min',{exact:true})).toBeVisible();await page.screenshot({path:join(tmpdir(),'train-yoga-desktop.png')});await page.getByRole('button',{name:'Move step 1 down in section 1',exact:true}).click();await expect(page.locator('.yoga-section').first().locator('.yoga-step').first()).toContainText('Guided Breathing');
 await page.getByRole('button',{name:'Move step 2 up in section 1',exact:true}).click();await expect(page.locator('.yoga-section').first().locator('.yoga-step').first()).toContainText('Easy Seat');
 const transfer=await page.evaluateHandle(()=>new DataTransfer());await page.getByRole('button',{name:'Drag step 1 in section 1',exact:true}).dispatchEvent('dragstart',{dataTransfer:transfer});await page.locator('.yoga-section').first().locator('.yoga-step').nth(1).dispatchEvent('drop',{dataTransfer:transfer});await expect(page.locator('.yoga-section').first().locator('.yoga-step').first()).toContainText('Guided Breathing');await page.getByRole('button',{name:'Move step 2 up in section 1',exact:true}).click();
 await page.getByRole('button',{name:'Move section 1 down',exact:true}).click();await expect(page.getByRole('textbox',{name:'Section 1 title',exact:true})).toHaveValue('Warm-Up');await page.getByRole('button',{name:'Move section 2 up',exact:true}).click();
 const sectionTransfer=await page.evaluateHandle(()=>new DataTransfer());await page.getByRole('button',{name:'Drag section 1',exact:true}).dispatchEvent('dragstart',{dataTransfer:sectionTransfer});await page.locator('.yoga-section').nth(1).dispatchEvent('drop',{dataTransfer:sectionTransfer});await expect(page.getByRole('textbox',{name:'Section 1 title',exact:true})).toHaveValue('Warm-Up');await page.getByRole('button',{name:'Move section 2 up',exact:true}).click();
 await page.locator('.yoga-section').first().getByRole('button',{name:'Edit',exact:true}).first().click();await page.getByRole('spinbutton',{name:'Hold / breath count',exact:true}).fill('120');await page.getByRole('button',{name:'Apply step changes'}).click();
 await page.getByRole('button',{name:'Save Draft',exact:true}).click();await expect(page.getByText('All changes saved',{exact:false})).toBeVisible();
 await page.getByRole('button',{name:'Preview',exact:true}).click();await expect(page.getByRole('timer')).toHaveText('2:00');await page.getByRole('button',{name:'Resume',exact:true}).click();await expect(page.getByRole('button',{name:'Pause',exact:true})).toBeVisible();await page.getByRole('button',{name:'Pause',exact:true}).click();await page.getByRole('button',{name:'Next pose',exact:true}).click();await expect(page.getByRole('heading',{name:'Guided Breathing',exact:true})).toBeVisible();await page.getByRole('button',{name:'Previous pose',exact:true}).click();await page.getByRole('button',{name:'Back',exact:true}).click();
 await page.getByRole('button',{name:'Publish',exact:true}).click();await expect(page.getByRole('button',{name:'Assign to Trainee',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Assign to Trainee',exact:true}).click();await page.getByRole('combobox',{name:'Trainee',exact:true}).selectOption('client-jamie');await page.getByRole('button',{name:'Confirm assignment',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.getByRole('button',{name:'Client Train & track'}).click();await expect(page.getByRole('navigation').getByRole('button',{name:'Exercise library',exact:true})).toHaveCount(0);await nav(page,'My yoga');const assigned=page.locator('.yoga-flow-card').filter({has:page.getByRole('heading',{name:'Browser yoga gratitude',exact:true})});await assigned.getByRole('button',{name:'Start class'}).click();await expect(page.getByRole('button',{name:'Publish',exact:true})).toHaveCount(0);
 const bootstrap=await (await page.request.get('/api/bootstrap')).json();expect(bootstrap.exercises.every(e=>bootstrap.plans.some(p=>p.items.some(i=>i.exerciseId===e.id)))).toBeTruthy();expect((await page.request.get('/api/yoga/poses')).status()).toBe(403);expect((await page.request.get('/api/yoga/flows')).status()).toBe(403);
 const count=await page.locator('.yoga-outline li').count();for(let i=1;i<count;i++)await page.getByRole('button',{name:'Next pose',exact:true}).click();await page.getByRole('button',{name:'Complete class',exact:true}).click();await expect(page.locator('.yoga-flow-card').filter({has:page.getByRole('heading',{name:'Browser yoga gratitude',exact:true})})).toContainText('Completed');await page.reload();await nav(page,'My yoga');await expect(page.locator('.yoga-flow-card').filter({has:page.getByRole('heading',{name:'Browser yoga gratitude',exact:true})})).toContainText('Completed');
});
test('mobile pose selection, steps, independent reusable blocks, and responsive preview',async({page})=>{
 await login(page);await nav(page,'Yoga');await page.getByRole('button',{name:'+ Create New Flow',exact:true}).click();await page.setViewportSize({width:390,height:844});await noOverflow(page);await page.screenshot({path:join(tmpdir(),'train-yoga-mobile.png')});
 await page.locator('.yoga-section').first().getByRole('button',{name:'+ Add Pose',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('textbox',{name:'Search poses to add',exact:true}).fill('Easy Seat');await page.getByRole('button').filter({has:page.getByText('Easy Seat',{exact:true})}).click();await page.getByRole('button',{name:'Add to Sequence (1)',exact:true}).click();await expect(page.locator('.yoga-section').first().locator('.yoga-step')).toHaveCount(1);
 await page.locator('.yoga-section').first().getByRole('button',{name:'+ Add Reusable Block',exact:true}).click();await page.getByRole('combobox',{name:'Block',exact:true}).selectOption('yoga-block-1');await page.getByLabel('Block repetitions').fill('2');await page.getByRole('button',{name:'Insert block',exact:true}).click();await expect(page.locator('.yoga-section').first().locator('.yoga-step')).toHaveCount(23);await noOverflow(page);
 await page.locator('.yoga-section').first().getByRole('button',{name:'Save selected poses as block',exact:true}).click();await page.getByRole('textbox',{name:'Block name',exact:true}).fill('Mobile custom block');await page.getByRole('button',{name:'Save reusable block',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('button',{name:'Save Draft',exact:true}).click();await expect(page.getByText('All changes saved',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Preview',exact:true}).click();await expect(page.getByRole('heading',{name:'Easy Seat',exact:true})).toBeVisible();await noOverflow(page);await page.getByRole('button',{name:'Back',exact:true}).click();await page.getByRole('button',{name:'Back to flows',exact:true}).click();await page.getByRole('tab',{name:'Reusable Blocks',exact:true}).click();const b=page.locator('.yoga-flow-card').filter({has:page.getByRole('heading',{name:'Mobile custom block',exact:true})});await expect(b).toBeVisible();await b.getByRole('button',{name:'Edit block',exact:true}).click();await page.getByRole('textbox',{name:'Block description'}).fill('Mobile edit preserved');await page.getByRole('button',{name:'Save block',exact:true}).click();await expect(b).toContainText('Mobile edit preserved');await noOverflow(page);
});
test('coach manages pose instructions, aliases, props and active status',async({page})=>{
 await login(page);await nav(page,'Yoga');await page.getByRole('tab',{name:'Pose Library',exact:true}).click();await page.getByRole('button',{name:'+ Add pose',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('textbox',{name:'English name',exact:true}).fill('Browser Supported Seat');await dialog.getByRole('textbox',{name:'Sanskrit name',exact:true}).fill('Sukhasana (supported variation)');for(const [label,value] of [['Instructions','Sit on a stable chair with feet supported.'],['Alignment cues','Keep the spine long and shoulders relaxed.'],['Modifications','Place blocks under the feet if needed.'],['Contraindications & safety','Stop if there is pain or dizziness.']])await dialog.getByRole('textbox',{name:label,exact:true}).fill(value);await dialog.getByRole('textbox',{name:'aliases (comma-separated)',exact:true}).fill('Chair Easy Seat');await dialog.getByRole('textbox',{name:'equipment (comma-separated)',exact:true}).fill('Chair, Blocks');await dialog.getByRole('button',{name:'Save pose',exact:true}).click();await expect(dialog).toHaveCount(0);await page.getByRole('textbox',{name:'Search yoga poses',exact:true}).fill('Chair Easy Seat');const card=page.locator('.yoga-pose-card').filter({has:page.getByRole('heading',{name:'Browser Supported Seat',exact:true})});await card.getByRole('button',{name:'View instructions',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Keep the spine long');await expect(page.getByRole('dialog')).toContainText('Video to come.');await page.getByRole('button',{name:'Close dialog',exact:true}).click();await card.getByRole('button',{name:'Edit',exact:true}).click();await page.getByRole('checkbox',{name:'Active',exact:true}).uncheck();await page.getByRole('button',{name:'Save pose',exact:true}).click();await expect(card).toHaveCount(0);await page.getByRole('combobox',{name:'Pose status',exact:true}).selectOption('Inactive');await expect(card).toBeVisible();
});

test('calendar assigns a whole sequence and timer advances, pauses and stops at final pose',async({page})=>{
 await login(page);const all=await (await page.request.get('/api/yoga/flows')).json();
 const copy=await (await page.request.post(`/api/yoga/flows/${all[0].id}/duplicate`,{data:{}})).json();
 const base=copy.sections[0].steps[0];
 await page.request.patch(`/api/yoga/flows/${copy.id}`,{data:{title:'Automatic calendar yoga',status:'Published',sections:[{title:'Timer practice',steps:[{...base,overrideSeconds:1},{...base,label:'Second',poseId:null,kind:'Breathing',overrideSeconds:1},{...base,label:'Closing pause',poseId:null,kind:'Pause',overrideSeconds:1498}]}]}});
 await nav(page,'Schedule');await page.getByRole('button',{name:'Add yoga class',exact:true}).click();
 await page.getByRole('combobox',{name:'Yoga sequence',exact:true}).selectOption(copy.id);
 await page.getByRole('combobox',{name:'Client',exact:true}).selectOption('client-jamie');
 await page.getByRole('button',{name:'Add to calendar',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.getByRole('button',{name:'Client Train & track'}).click();await nav(page,'Schedule');
 await page.locator('.schedule-agenda-item').filter({hasText:'Automatic calendar yoga'}).getByRole('button',{name:'Start yoga class'}).click();
 await page.clock.install();await page.getByRole('button',{name:'Resume',exact:true}).click();await page.clock.runFor(1200);await expect(page.getByRole('heading',{name:'Second',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Pause',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Pause',exact:true}).click();await page.clock.runFor(5000);await expect(page.getByRole('heading',{name:'Second',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Resume',exact:true}).click();await page.clock.runFor(1200);await expect(page.getByRole('heading',{name:'Closing pause',exact:true})).toBeVisible();
 await page.clock.fastForward(1499000);await expect(page.getByRole('timer')).toHaveText('0:00');await expect(page.getByRole('button',{name:'Resume',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Next pose',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'Complete class',exact:true}).click();await expect(page.locator('.schedule-agenda-item').filter({hasText:'Automatic calendar yoga'})).toContainText('Completed');
});
test('forgot password guidance and private reset link choose a new password',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Forgot password?',exact:true}).click();await page.getByRole('textbox',{name:'Email address',exact:true}).fill('jamie@form.fit');await page.getByRole('button',{name:'Send reset link',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Ask your coach');
 await login(page);await page.getByRole('navigation').getByRole('button',{name:/^My clients/}).click();await page.locator('.client-card').filter({has:page.getByRole('heading',{name:'Jamie Chen',exact:true})}).getByRole('button',{name:'Create password reset link',exact:true}).click();const link=await page.getByRole('textbox',{name:'Secure reset link',exact:true}).inputValue();await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('button',{name:'Sign out',exact:true}).click();await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeVisible();
 await page.goto(link);await page.getByLabel('New password',{exact:true}).fill('BrowserRecovery123!');await page.getByLabel('Confirm new password',{exact:true}).fill('BrowserRecovery123!');await page.getByRole('button',{name:'Reset password',exact:true}).click();await expect(page.getByRole('status')).toContainText('Password updated');
 // Restore the shared demo account for the other browser contracts.
 await page.request.post('/api/auth/login',{data:{email:'admin@form.fit',password:'FormDemo123!'}});await page.request.patch('/api/users/user-jamie',{data:{password:'FormDemo123!'}});await page.request.post('/api/auth/logout');
});
