import { test, expect } from '@playwright/test';

test('live library workouts copy independently and body fat assessments persist', async ({ page }) => {
  const name = `Reusable preview ${Date.now().toString(36)}`, date = new Date().toISOString().slice(0, 10);
  await page.goto('/');
  await page.getByRole('button', { name: 'Coach Plan & guide', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Good/ })).toBeVisible();
  await page.getByRole('navigation').getByRole('button', { name: 'Workout plans', exact: true }).click();
  await page.locator('.page-heading').getByRole('button', { name: 'Build a workout', exact: true }).click();
  let dialog = page.getByRole('dialog');
  await dialog.getByRole('combobox', { name: 'Client', exact: true }).selectOption('');
  await expect(dialog.getByLabel('Workout date')).toHaveCount(0);
  await dialog.getByLabel('Workout name').fill(name);
  await dialog.getByRole('button', { name: /Bodyweight squat/ }).click();
  await dialog.getByLabel('Bodyweight squat Rest (sec)', { exact: true }).fill('75');
  await dialog.getByLabel('Coaching note', { exact: true }).fill('Preview test cue');
  await dialog.getByRole('button', { name: 'Save workout', exact: true }).click();
  await expect(dialog).toBeHidden();
  const template = page.locator('.workout-template-library article').filter({ has: page.getByRole('heading', { name, exact: true }) });
  await template.getByRole('button', { name: 'Copy to client', exact: true }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByRole('combobox', { name: 'Client', exact: true }).selectOption('client-jamie');
  await dialog.getByLabel('Workout date').fill(date);
  await dialog.getByRole('button', { name: 'Copy workout', exact: true }).click();
  await expect(dialog).toBeHidden();
  await page.getByRole('button', { name: /^Daily routines/ }).click();
  await template.getByRole('button', { name: 'Edit workout', exact: true }).click();
  await page.getByRole('dialog').getByLabel('Bodyweight squat Sets', { exact: true }).fill('5');
  await page.getByRole('dialog').getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeHidden();
  await page.getByRole('button', { name: 'Client calendar', exact: true }).click();
  const copy = page.locator('article').filter({ has: page.getByRole('heading', { name, exact: true }) });
  await expect(copy.getByText('3 × 10 reps · Bodyweight', { exact: true })).toBeVisible();
  await page.getByRole('navigation').getByRole('button', { name: 'Progress & assessments', exact: true }).click();
  await page.getByRole('combobox', { name: 'Select client', exact: true }).selectOption('client-jamie');
  await page.getByRole('button', { name: 'Body fat %', exact: true }).click();
  await page.getByRole('dialog').getByLabel('Body fat (%)', { exact: true }).fill('25.5');
  await page.getByRole('dialog').getByLabel(/^Notes/).fill(`Sample preview assessment ${name}`);
  await page.getByRole('dialog').getByRole('button', { name: 'Save assessment', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeHidden();
  await page.reload();
  await page.getByRole('navigation').getByRole('button', { name: 'Progress & assessments', exact: true }).click();
  await page.getByRole('combobox', { name: 'Select client', exact: true }).selectOption('client-jamie');
  await expect(page.locator('.pg-stat').filter({ hasText: 'Body fat percentage' }).getByText('25.5', { exact: true })).toBeVisible();
});
