import { useState, type FormEvent } from 'react';
import { Plus, Search, ArrowUpRight, Mail, Dumbbell, Users } from 'lucide-react';
import type { Data, Client, Page } from '../types';
import { api } from '../api';
import { RecoveryLinkButton } from './PasswordRecovery';
import Modal from './Modal';
import InviteClient from './InviteClient';
export default function Clients({data,refresh,notify,navigate}:{data:Data;refresh:()=>Promise<void>;notify:(m:string)=>void;navigate:(p:Page)=>void}) {
 const [inviteOpen,setInviteOpen]=useState(false);
 const [query,setQuery]=useState('');const [editing,setEditing]=useState<Client|null|undefined>();const [error,setError]=useState('');const [saving,setSaving]=useState(false);
 const [name,setName]=useState('');const [email,setEmail]=useState('');const [goal,setGoal]=useState('');const [password,setPassword]=useState('');
 const open=(client:Client|null)=>{setEditing(client);setName(client?.name||'');setEmail(client?.email||'');setGoal(client?.goal||'');setPassword('');setError('');};
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setError('');try{await api(editing?`/clients/${editing.id}`:'/clients',editing?'PATCH':'POST',editing?{name,email,goal}:{name,email,goal,password,equipment:[]});await refresh();setEditing(undefined);notify(editing?'Client updated':'Client added. Share their email and password securely.');}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 async function revoke(id:string){try{await api(`/invitations/${id}`,'DELETE');await refresh();notify('Invitation revoked.');}catch(failure){notify((failure as Error).message);}}
 const invitations=data.invitations.filter(invitation=>invitation.status==='Pending'||invitation.status==='Expired');
 const clients=data.clients.filter(c=>`${c.name} ${c.email} ${c.goal}`.toLowerCase().includes(query.toLowerCase()));
 return <><div className="page-heading clients-page-heading"><div><span className="eyebrow">YOUR PEOPLE</span><h1>Clients<span className="heading-dot">.</span></h1><p>Every client has a different story. Help them write their next chapter.</p></div><div className="client-heading-actions"><button className="button secondary" onClick={()=>open(null)}><Plus size={17}/>Add client</button><button className="button primary" onClick={()=>setInviteOpen(true)}><Mail size={17}/>Invite client</button></div></div>
 <div className="toolbar"><div className="search-input"><Search size={18}/><input aria-label="Search clients" placeholder="Find a client…" value={query} onChange={e=>setQuery(e.target.value)}/></div><span className="muted">{clients.length} {clients.length===1?'client':'clients'}</span></div>
 {invitations.length>0&&<section className="panel client-invitations"><h2>Client invitations</h2><p>Clients appear below when they finish registering. Create a new invitation if a link expires or needs to be replaced.</p>{invitations.map(invitation=><div className="invitation-row" key={invitation.id}><div><strong>{invitation.name}</strong><span>{invitation.email}</span></div><span className="badge sage">{invitation.status}</span>{invitation.status==='Pending'&&<button className="text-button" onClick={()=>revoke(invitation.id)}>Revoke</button>}</div>)}</section>}
 <div className="client-grid">{clients.map(c=>{const plans=data.plans.filter(p=>p.clientId===c.id);const completed=data.logs.filter(l=>l.clientId===c.id).length;return <article className="panel client-card" key={c.id}><div className="client-card-top"><div className="avatar large" style={{background:c.color}}>{c.name.split(' ').map(n=>n[0]).join('').slice(0,2)}</div><span className="badge sage">Active</span></div><h2>{c.name}</h2><RecoveryLinkButton userId={c.userId}/><div className="client-email"><Mail size={14}/>{c.email}</div><p className="client-goal">{c.goal||'Ready for their next step.'}</p><div className="client-card-stats"><div><strong>{plans.length}</strong><span>Workouts assigned</span></div><div><strong>{completed}</strong><span>Completed</span></div></div><div className="equipment-preview"><Dumbbell size={15}/>{c.equipment.length?c.equipment.slice(0,3).join(' · '):'Bodyweight training'}{c.equipment.length>3?' + more':''}</div><div className="client-card-bottom"><button className="text-button" onClick={()=>open(c)}>Edit profile<ArrowUpRight size={15}/></button><button className="button secondary small" onClick={()=>navigate('workouts')}>Plan workout</button></div></article>})}</div>
 {!clients.length&&<div className="empty-state"><Users size={32}/><h3>{query?'No clients found':'Your coaching journey starts here'}</h3><p>{query?'Try a different name or goal.':'Invite your first client to register and start planning together.'}</p></div>}
 {editing!==undefined&&<Modal title={editing?'Edit client':'Welcome a new client'} onClose={()=>setEditing(undefined)}><form onSubmit={save}><p className="modal-intro">{editing?'Keep their profile up to date.':'Create their account and share the sign-in details securely.'}</p><div className="form-grid"><label className="field">Full name<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="Jamie Chen"/></label><label className="field">Email address<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="jamie@example.com"/></label>{!editing&&<label className="field full-width">Initial password<input type="password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/><small>At least 8 characters. Give this to your client outside the app.</small></label>}<label className="field full-width">Training goal<textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Build strength, feel confident, and stay consistent." rows={3}/></label></div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setEditing(undefined)}>Cancel</button><button className="button primary" disabled={saving}>{saving?'Saving…':editing?'Save changes':'Add client'}</button></div></form></Modal>}
 {inviteOpen&&<InviteClient data={data} refresh={refresh} onClose={()=>setInviteOpen(false)}/>}
 </>;
}
