import type { YogaPose, YogaStep } from '../yoga-types';
import Modal from './Modal';
import { useState } from 'react';
import { stepSeconds } from '../../shared/yoga-timing.mjs';
import { minutes } from './YogaShared';
export default function YogaStepEditor({step,pose,onSave,onClose}:{step:YogaStep;pose?:YogaPose;onSave:(s:YogaStep)=>void;onClose:()=>void}) {
 const [draft,setDraft]=useState(step);
 return <Modal title={`Edit ${pose?.name??step.label}`} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(draft);onClose();}}><div className="form-grid">{!pose&&<label className="field">Step label<input required value={draft.label} onChange={e=>setDraft({...draft,label:e.target.value})}/></label>}<label className="field">Hold unit<select value={draft.unit} onChange={e=>setDraft({...draft,unit:e.target.value as YogaStep['unit']})}><option>seconds</option><option>breaths</option></select></label>{([['hold','Hold / breath count',1,draft.unit==='breaths'?300:1800],['secondsPerBreath','Seconds per breath',2,30],['repetitions','Repetitions / rounds',1,30],['transitionSeconds','Transition per hold (seconds)',0,300],['restSeconds','Rest per hold (seconds)',0,600]] as const).map(([key,label,min,max])=><label className="field" key={key}>{label}<input type="number" required min={min} max={max} value={draft[key]} onChange={e=>setDraft({...draft,[key]:Number(e.target.value)})}/></label>)}<label className="field">Side<select value={draft.side} onChange={e=>setDraft({...draft,side:e.target.value as YogaStep['side']})}>{['Center','Left','Right','Both'].map(v=><option key={v}>{v}</option>)}</select><small>Both repeats the hold, transition and rest on each side.</small></label><label className="field">Total step timing override (seconds)<input type="number" min={1} max={3600} value={draft.overrideSeconds??''} onChange={e=>setDraft({...draft,overrideSeconds:e.target.value?Number(e.target.value):null})}/><small>Overrides the entire step including rounds, both sides and rest.</small></label><label className="field">Transition notes<textarea value={draft.transitionNotes} onChange={e=>setDraft({...draft,transitionNotes:e.target.value})}/></label><label className="field">Instructor cues<textarea value={draft.cues} onChange={e=>setDraft({...draft,cues:e.target.value})}/></label></div><p>Calculated step duration: {minutes(stepSeconds(draft))}</p><div className="modal-actions"><button className="button primary">Apply step changes</button></div></form></Modal>;
}
