import { useEffect, useState } from 'react';
import { api } from '../api';
import type { YogaPose } from '../yoga-types';
import Modal from './Modal';
import { categories, difficulties, positions, PoseArt } from './YogaShared';
import './Yoga.css';
const blank=():YogaPose=>({id:'',name:'',sanskritName:'',chineseName:'',aliases:[],category:'Standing',difficulty:'Beginner',targetAreas:'',movementType:'Static',position:'Standing',recommendedHold:30,breathInstructions:'',instructions:'',alignmentCues:'',commonMistakes:'',modifications:'',contraindications:'',equipment:['Yoga mat'],imageUrl:'',videoUrl:'',active:true});
const fields: [keyof YogaPose,string][]=[['name','English name'],['sanskritName','Sanskrit name'],['chineseName','Chinese name'],['targetAreas','Target areas'],['movementType','Movement type'],['breathInstructions','Breath instructions'],['instructions','Instructions'],['alignmentCues','Alignment cues'],['commonMistakes','Common mistakes'],['modifications','Modifications'],['contraindications','Contraindications & safety'],['imageUrl','Image URL'],['videoUrl','Video URL']];
export default function YogaPoseLibrary({notify}:{notify:(message:string)=>void}) {
 const [poses,setPoses]=useState<YogaPose[]>([]),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[difficulty,setDifficulty]=useState(''),[active,setActive]=useState('Active'),[selected,setSelected]=useState<YogaPose|null>(null),[editing,setEditing]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>api<YogaPose[]>('/yoga/poses').then(setPoses);useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 const visible=poses.filter(p=>[p.name,p.sanskritName,p.chineseName,p.targetAreas,...p.aliases].join(' ').toLowerCase().includes(search.toLowerCase())&&(!category||p.category===category||p.position===category)&&(!difficulty||p.difficulty===difficulty)&&(!active||p.active===(active==='Active')));
 async function save(e:React.FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setError('');try{const {id,...body}=selected;await api(id?`/yoga/poses/${id}`:'/yoga/poses',id?'PATCH':'POST',{...body,aliases:body.aliases.filter(Boolean),equipment:body.equipment.filter(Boolean)});await load();setSelected(null);notify('Yoga pose saved.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="yoga-page"><div className="page-heading"><div><span className="eyebrow">YOGA · POSE LIBRARY</span><h1>Yoga pose library</h1><p>Clear guidance and supported options for every class.</p></div><button className="button primary" onClick={()=>{setSelected(blank());setEditing(true);setError('');}}>+ Add pose</button></div><div className="yoga-filters"><input aria-label="Search yoga poses" placeholder="Search English, Sanskrit or aliases" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Pose category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories / positions</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select aria-label="Pose difficulty" value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="">All difficulties</option>{difficulties.map(c=><option key={c}>{c}</option>)}</select><select aria-label="Pose status" value={active} onChange={e=>setActive(e.target.value)}><option>Active</option><option>Inactive</option><option value="">All statuses</option></select></div>{error&&!selected&&<p role="alert" className="form-error">{error}</p>}<p className="muted">{visible.length} poses</p><div className="card-grid">{visible.map(p=><article className="panel yoga-pose-card" key={p.id}><PoseArt pose={p}/><h3>{p.name}</h3><p className="muted">{p.sanskritName}</p><div className="yoga-tags"><span className="tag">{p.category}</span><span className="tag">{p.difficulty}</span><span className="tag">{p.recommendedHold}s</span>{!p.active&&<span className="badge">Inactive</span>}</div><div className="yoga-actions"><button className="button secondary" onClick={()=>{setSelected(p);setEditing(false);setError('');}}>View instructions</button><button className="button secondary" onClick={()=>{setSelected(p);setEditing(true);setError('');}}>Edit</button></div></article>)}</div>{!visible.length&&<div className="empty-state panel">No matching poses. Adjust the search or filters.</div>}
 {selected&&<Modal title={editing?(selected.id?'Edit yoga pose':'Add yoga pose'):selected.name} onClose={()=>!busy&&setSelected(null)} className="yoga-modal">{editing?<form onSubmit={save}><div className="form-grid">{fields.map(([key,label])=><label className="field" key={key}>{label}{['instructions','alignmentCues','modifications','contraindications','commonMistakes','breathInstructions'].includes(key)?<textarea required={['instructions','alignmentCues','modifications','contraindications'].includes(key)} value={String(selected[key])} onChange={e=>setSelected({...selected,[key]:e.target.value})}/>:<input required={key==='name'} type={key.endsWith('Url')?'url':'text'} value={String(selected[key])} onChange={e=>setSelected({...selected,[key]:e.target.value})}/>}</label>)}{([['category',categories],['difficulty',difficulties],['position',positions]] as const).map(([key,values])=><label className="field" key={key}>{key}<select value={selected[key]} onChange={e=>setSelected({...selected,[key]:e.target.value})}>{values.map(v=><option key={v}>{v}</option>)}</select></label>)}<label className="field">Recommended hold (seconds)<input type="number" min={1} max={1800} value={selected.recommendedHold} onChange={e=>setSelected({...selected,recommendedHold:Number(e.target.value)})}/></label>{(['aliases','equipment'] as const).map(key=><label className="field" key={key}>{key} (comma-separated)<input value={selected[key].join(', ')} onChange={e=>setSelected({...selected,[key]:e.target.value.split(',').map(s=>s.trim())})}/></label>)}<label className="field">Active<input type="checkbox" checked={selected.active} onChange={e=>setSelected({...selected,active:e.target.checked})}/></label></div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button className="button primary" disabled={busy}>Save pose</button></div></form>:<><PoseArt pose={selected}/><p>{selected.sanskritName} · {selected.difficulty}</p>{fields.slice(5,11).map(([key,label])=><div className="yoga-guidance" key={key}><h4>{label}</h4><p>{String(selected[key])}</p></div>)}{selected.videoUrl?<a className="button secondary" href={selected.videoUrl} target="_blank" rel="noreferrer">Watch demonstration</a>:<p className="muted">Video to come.</p>}</>}</Modal>}
 </div>;
}
