import { useEffect, useState } from 'react';
import { GripVertical } from 'lucide-react';
import type { YogaBlock, YogaFlow, YogaPose, YogaStep } from '../yoga-types';
import type { Data } from '../types';
import { api } from '../api';
import { flowSeconds, stepSeconds } from '../../shared/yoga-timing.mjs';
import { difficulties, flowPayload, minutes, move, newStep, PoseArt, styles, Tags } from './YogaShared';
import YogaSelection from './YogaSelection';
import YogaStepEditor from './YogaStepEditor';
import YogaPlayer from './YogaPlayer';
import Modal from './Modal';
const metadata:[keyof YogaFlow,string][]=[['title','Class title'],['theme','Theme'],['quote','Inspirational quote'],['quoteAttribution','Quote attribution'],['description','Description'],['targetAreas','Target areas'],['openingIntention','Opening intention'],['closingReflection','Closing reflection'],['instructorNotes','Instructor notes']];
export default function YogaFlowEditor({initial,poses,blocks,data,onBack,onSaved,notify}:{initial:YogaFlow;poses:YogaPose[];blocks:YogaBlock[];data:Data;onBack:()=>void;onSaved:(flow:YogaFlow)=>void;notify:(m:string)=>void}) {
 const [availableBlocks,setAvailableBlocks]=useState(blocks);
 const [assignmentDate,setAssignmentDate]=useState(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;});
 const [flow,setFlow]=useState(initial),[saved,setSaved]=useState(JSON.stringify(initial)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState(false),[collapsed,setCollapsed]=useState<number[]>([]),[selection,setSelection]=useState<number|null>(null),[edit,setEdit]=useState<{section:number;step:number}|null>(null),[blockSection,setBlockSection]=useState<number|null>(null),[blockId,setBlockId]=useState(blocks[0]?.id??''),[blockRounds,setBlockRounds]=useState(1),[assign,setAssign]=useState(false),[clientId,setClientId]=useState(data.clients[0]?.id??''),[leave,setLeave]=useState(false),[remove,setRemove]=useState<number|null>(null),[blockSave,setBlockSave]=useState<number|null>(null),[blockName,setBlockName]=useState(''),[blockSelected,setBlockSelected]=useState<number[]>([]);
 const dirty=JSON.stringify(flow)!==saved;
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const total=flowSeconds(flow),difference=total-flow.targetMinutes*60;
 function updateSteps(index:number,steps:YogaStep[]){setFlow({...flow,sections:flow.sections.map((s,i)=>i===index?{...s,steps}:s)});}
 function reorderSection(from:number,to:number){setFlow({...flow,sections:move(flow.sections,from,to)});setCollapsed([]);}
 async function save(status:YogaFlow['status']) {setBusy(true);setError('');try{const next=await api<YogaFlow>(flow.id?`/yoga/flows/${flow.id}`:'/yoga/flows',flow.id?'PATCH':'POST',flowPayload({...flow,status,equipment:flow.equipment.filter(Boolean)}));setFlow(next);setSaved(JSON.stringify(next));onSaved(next);notify(status==='Published'?'Yoga flow published.':'Draft saved.');return next;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
 async function assignFlow(){setBusy(true);setError('');try{await api(`/yoga/flows/${flow.id}/assign`,'POST',{clientId,date:assignmentDate});setAssign(false);notify('Published flow assigned to trainee.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function saveBlock(){if(blockSave===null)return;setBusy(true);try{const created=await api<YogaBlock>('/yoga/blocks','POST',{name:blockName,description:'Saved from a yoga flow',steps:flow.sections[blockSave].steps.filter((_,i)=>blockSelected.includes(i))});setAvailableBlocks([...availableBlocks,created]);setBlockId(created.id);setBlockSave(null);notify('Reusable block saved and ready to insert.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(preview)return <YogaPlayer flow={flow} poses={poses} onClose={()=>setPreview(false)}/>;
 return <div className="yoga-editor"><div className="page-heading"><div><span className="eyebrow">COACH DASHBOARD → YOGA → FLOW BUILDER</span><h1>Yoga Flow Builder</h1><p>{flow.title} · {flow.status} · {dirty?'Unsaved changes':'All changes saved'}</p></div><div className="yoga-actions"><button className="button secondary" onClick={()=>dirty?setLeave(true):onBack()} disabled={busy}>Back to flows</button><button className="button secondary" onClick={()=>save('Draft')} disabled={busy}>Save Draft</button><button className="button secondary" onClick={()=>setPreview(true)} disabled={busy}>Preview</button><button className="button primary" onClick={()=>save('Published')} disabled={busy}>Publish</button><button className="button secondary" disabled={busy||dirty||flow.status!=='Published'||!flow.id||!data.clients.length} onClick={()=>setAssign(true)}>Assign to Trainee</button></div></div>{error&&<p className="form-error" role="alert">{error}</p>}
 <section className="panel yoga-info"><h2>Class information</h2><Tags flow={flow}/><div className="form-grid">{metadata.map(([key,label])=><label className="field" key={key}>{label}{['description','openingIntention','closingReflection','instructorNotes'].includes(key)?<textarea value={String(flow[key])} onChange={e=>setFlow({...flow,[key]:e.target.value})}/>:<input value={String(flow[key])} onChange={e=>setFlow({...flow,[key]:e.target.value})}/>}</label>)}{([['style','Yoga style',styles],['difficulty','Difficulty',difficulties]] as const).map(([key,label,values])=><label className="field" key={key}>{label}<select value={flow[key]} onChange={e=>setFlow({...flow,[key]:e.target.value})}>{values.map(v=><option key={v}>{v}</option>)}</select></label>)}<label className="field">Target duration (minutes)<input type="number" min={25} max={55} value={flow.targetMinutes} onChange={e=>setFlow({...flow,targetMinutes:Number(e.target.value)})}/></label><label className="field">Equipment / props (comma-separated)<input value={flow.equipment.join(', ')} onChange={e=>setFlow({...flow,equipment:e.target.value.split(',').map(v=>v.trim())})}/></label></div>{flow.references.length>0&&<details><summary>Research references & attribution</summary>{flow.references.map((r,i)=><p key={i}><a href={r.url} target="_blank" rel="noreferrer">{r.name}</a> · {r.attribution}</p>)}</details>}</section>
 <div className="yoga-sequence-heading"><div><h2>Class sequence</h2><p className="muted">Drag handles or use Move up / Move down. Repeated poses share one library entry.</p></div><button className="button secondary" onClick={()=>setFlow({...flow,sections:[...flow.sections,{title:'New section',steps:[]}]})}>+ Add section</button></div>
 {flow.sections.map((section,si)=><section className="panel yoga-section" key={si} data-section={si} onDragOver={e=>e.preventDefault()} onDrop={e=>{const raw=e.dataTransfer.getData('application/yoga-section');if(raw){e.preventDefault();reorderSection(Number(raw),si);}else{const stepData=e.dataTransfer.getData('application/yoga-step');if(stepData){const [from,index]=JSON.parse(stepData) as number[];if(from!==si){e.preventDefault();const sections=structuredClone(flow.sections);sections[si].steps.push(sections[from].steps.splice(index,1)[0]);setFlow({...flow,sections});}}}}}><div className="yoga-section-heading"><button type="button" className="icon-button yoga-grip" draggable aria-label={`Drag section ${si+1}`} onDragStart={e=>{e.dataTransfer.setData('application/yoga-section',String(si));e.dataTransfer.effectAllowed='move';}}><GripVertical size={20}/></button><span className="badge">{si+1}</span><input className="yoga-section-title" aria-label={`Section ${si+1} title`} value={section.title} onChange={e=>setFlow({...flow,sections:flow.sections.map((s,i)=>i===si?{...s,title:e.target.value}:s)})}/><span className="tag">{minutes(section.steps.reduce((s,p)=>s+stepSeconds(p),0))}</span><button className="button secondary" aria-expanded={!collapsed.includes(si)} onClick={()=>setCollapsed(collapsed.includes(si)?collapsed.filter(i=>i!==si):[...collapsed,si])}>{collapsed.includes(si)?'Expand':'Collapse'}</button></div><p className="muted yoga-section-summary">{section.steps.map(s=>poses.find(p=>p.id===s.poseId)?.name??s.label).join(' · ')||'Add poses, breathwork or a reusable block.'}</p><div className="yoga-actions"><button className="button secondary" onClick={()=>setSelection(si)}>+ Add Pose</button><button className="button secondary" onClick={()=>{setBlockSection(si);setBlockRounds(1);}}>+ Add Reusable Block</button><button className="button secondary" onClick={()=>updateSteps(si,[...section.steps,newStep(undefined,'Breathing')])}>+ Breathing</button><button className="button secondary" onClick={()=>updateSteps(si,[...section.steps,newStep(undefined,'Pause')])}>+ Pause</button><button className="button secondary" disabled={!section.steps.length} onClick={()=>{setBlockSave(si);setBlockName(section.title);setBlockSelected(section.steps.map((_,i)=>i));}}>Save selected poses as block</button><button className="button secondary" aria-label={`Move section ${si+1} up`} disabled={si===0} onClick={()=>reorderSection(si,si-1)}>Move up</button><button className="button secondary" aria-label={`Move section ${si+1} down`} disabled={si===flow.sections.length-1} onClick={()=>reorderSection(si,si+1)}>Move down</button><button className="button secondary" onClick={()=>{const sections=[...flow.sections];sections.splice(si+1,0,structuredClone({...section,id:undefined,title:`${section.title} (copy)`}));setFlow({...flow,sections});}}>Duplicate Section</button><button className="button ghost danger-text" onClick={()=>setRemove(si)}>Delete Section</button></div>
 {!collapsed.includes(si)&&<div className="yoga-steps">{section.steps.map((step,pi)=>{const pose=poses.find(p=>p.id===step.poseId);return <article className="yoga-step" key={pi} onDragOver={e=>e.preventDefault()} onDrop={e=>{const raw=e.dataTransfer.getData('application/yoga-step');if(!raw)return;e.preventDefault();e.stopPropagation();const [fromSection,fromStep]=JSON.parse(raw) as number[];const sections=structuredClone(flow.sections);if(fromSection===si)sections[si].steps=move(sections[si].steps,fromStep,pi);else{const [moved]=sections[fromSection].steps.splice(fromStep,1);sections[si].steps.splice(pi,0,moved);}setFlow({...flow,sections});}}><button className="icon-button yoga-grip" draggable aria-label={`Drag step ${pi+1} in section ${si+1}`} onDragStart={e=>{e.stopPropagation();e.dataTransfer.setData('application/yoga-step',JSON.stringify([si,pi]));e.dataTransfer.effectAllowed='move';}}><GripVertical size={18}/></button><PoseArt pose={pose}/><div className="yoga-step-content"><strong>{pi+1}. {pose?.name??step.label}</strong><small>{pose?.sanskritName}</small><div className="yoga-tags"><span className="tag">{step.hold} {step.unit}</span><span className="tag">{step.side}</span><span className="tag">× {step.repetitions}</span><span className="tag">{minutes(stepSeconds(step))}{step.overrideSeconds!==null?' override':''}</span></div>{step.transitionNotes&&<p>Transition: {step.transitionNotes}</p>}{step.cues&&<p>Cues: {step.cues}</p>}</div><div className="yoga-step-actions"><button className="button secondary" onClick={()=>setEdit({section:si,step:pi})}>Edit</button><button className="button secondary" onClick={()=>{const steps=[...section.steps];steps.splice(pi+1,0,structuredClone({...step,id:undefined}));updateSteps(si,steps);}}>Duplicate</button><button className="button ghost danger-text" onClick={()=>updateSteps(si,section.steps.filter((_,i)=>i!==pi))}>Delete</button><button className="button secondary" aria-label={`Move step ${pi+1} up in section ${si+1}`} disabled={pi===0} onClick={()=>updateSteps(si,move(section.steps,pi,pi-1))}>Move up</button><button className="button secondary" aria-label={`Move step ${pi+1} down in section ${si+1}`} disabled={pi===section.steps.length-1} onClick={()=>updateSteps(si,move(section.steps,pi,pi+1))}>Move down</button></div></article>;})}</div>}</section>)}
 <div className="panel yoga-duration" role="status"><strong>Total Class Duration: {minutes(total)}</strong><progress aria-label="Duration against target" value={Math.min(total,flow.targetMinutes*60)} max={flow.targetMinutes*60||1}/><div>Target: {flow.targetMinutes} minutes · Calculated: {minutes(total)} · Difference: {difference>0?'+':''}{minutes(difference)}</div>{difference!==0&&<p className="muted">The sequence is {difference<0?'shorter':'longer'} than your target. Adjust holds, repetitions or pauses as needed.</p>}</div>
 {selection!==null&&<YogaSelection poses={poses} onClose={()=>setSelection(null)} onInsert={selected=>updateSteps(selection,[...flow.sections[selection].steps,...selected.map(p=>newStep(p))])}/>}
 {edit&&<YogaStepEditor step={flow.sections[edit.section].steps[edit.step]} pose={poses.find(p=>p.id===flow.sections[edit.section].steps[edit.step].poseId)} onClose={()=>setEdit(null)} onSave={step=>updateSteps(edit.section,flow.sections[edit.section].steps.map((s,i)=>i===edit.step?step:s))}/>}
 {blockSection!==null&&<Modal title="Insert reusable block" onClose={()=>setBlockSection(null)}><p className="muted">Inserted steps are independent copies. Editing them leaves the template unchanged.</p><label className="field">Block<select value={blockId} onChange={e=>setBlockId(e.target.value)}>{availableBlocks.map(b=><option key={b.id} value={b.id}>{b.name} · {minutes(b.steps.reduce((s,p)=>s+stepSeconds(p),0))}</option>)}</select></label><label className="field">Block repetitions<input type="number" min={1} max={20} value={blockRounds} onChange={e=>setBlockRounds(Number(e.target.value))}/></label><div className="modal-actions"><button className="button primary" disabled={!blockId||!Number.isInteger(blockRounds)||blockRounds<1||blockRounds>20} onClick={()=>{const b=availableBlocks.find(b=>b.id===blockId);if(!b)return;updateSteps(blockSection,[...flow.sections[blockSection].steps,...Array.from({length:blockRounds},()=>structuredClone(b.steps).map(s=>({...s,id:undefined}))).flat()]);setBlockSection(null);}}>Insert block</button></div></Modal>}
 {blockSave!==null&&<Modal title="Save selected poses as block" onClose={()=>!busy&&setBlockSave(null)}><label className="field">Block name<input value={blockName} onChange={e=>setBlockName(e.target.value)}/></label><div className="yoga-block-checkboxes">{flow.sections[blockSave].steps.map((s,i)=><label key={i}><input type="checkbox" checked={blockSelected.includes(i)} onChange={()=>setBlockSelected(blockSelected.includes(i)?blockSelected.filter(n=>n!==i):[...blockSelected,i])}/>{i+1}. {poses.find(p=>p.id===s.poseId)?.name??s.label}</label>)}</div>{error&&<p role="alert">{error}</p>}<button className="button primary" disabled={busy||!blockName.trim()||!blockSelected.length} onClick={saveBlock}>Save reusable block</button></Modal>}
 {assign&&<Modal title="Assign yoga flow" onClose={()=>!busy&&setAssign(false)}><label className="field">Trainee<select value={clientId} onChange={e=>setClientId(e.target.value)}>{data.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field">Calendar date<input type="date" required value={assignmentDate} onChange={e=>setAssignmentDate(e.target.value)}/></label><p>A published copy with pose guidance will be assigned to this trainee.</p>{error&&<p role="alert">{error}</p>}<button className="button primary" disabled={busy||!clientId||!assignmentDate} onClick={assignFlow}>Confirm assignment</button></Modal>}
 {leave&&<Modal title="Unsaved changes" onClose={()=>setLeave(false)}><p>Save your draft before leaving, or discard these edits.</p><div className="modal-actions"><button className="button secondary" onClick={()=>setLeave(false)}>Keep editing</button><button className="button danger" onClick={onBack}>Discard edits</button><button className="button primary" disabled={busy} onClick={async()=>{if(await save('Draft'))onBack();}}>Save and leave</button></div></Modal>}
 {remove!==null&&<Modal title="Delete section?" onClose={()=>setRemove(null)}><p>This removes the section and its steps from this draft.</p><button className="button danger" onClick={()=>{setFlow({...flow,sections:flow.sections.filter((_,i)=>i!==remove)});setCollapsed([]);setRemove(null);}}>Confirm delete section</button></Modal>}
 </div>;
}
