import { useEffect, useRef, useState } from 'react';
import type { YogaFlow, YogaPose } from '../yoga-types';
import { flowSeconds, sessionPhases } from '../../shared/yoga-timing.mjs';
import { PoseArt, Tags, duration, minutes } from './YogaShared';
export default function YogaPlayer({flow,poses,onClose,onComplete}:{flow:YogaFlow;poses:YogaPose[];onClose:()=>void;onComplete?:()=>Promise<void>}) {
 const items=flow.sections.flatMap(section=>section.steps.map(step=>({section:section.title,step,phases:sessionPhases(step)})));
 const [index,setIndex]=useState(0),[elapsed,setElapsed]=useState(0),[playing,setPlaying]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const clock=useRef({start:0,elapsed:0});
 const item=items[index],total=item?.phases.reduce((s,p)=>s+p.seconds,0)??0;
 useEffect(()=>{if(!playing)return;clock.current={start:Date.now(),elapsed};const timer=setInterval(()=>{const next=clock.current.elapsed+Math.floor((Date.now()-clock.current.start)/1000);setElapsed(Math.min(next,total));if(next>=total)setPlaying(false);},200);return()=>clearInterval(timer);},[playing,index,total]);
 function go(next:number){setPlaying(false);setElapsed(0);setIndex(next);}
 async function complete(){if(!onComplete)return;setBusy(true);try{await onComplete();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!item)return <div className="panel empty-state"><h2>No poses yet</h2><p>Add poses to preview your class.</p><button className="button secondary" onClick={onClose}>Back to builder</button></div>;
 const pose=poses.find(p=>p.id===item.step.poseId);let consumed=0;const phase=item.phases.find(p=>{consumed+=p.seconds;return elapsed<consumed;})??{label:'Step finished',seconds:0};
 return <div className="yoga-player"><div className="page-heading"><div><span className="eyebrow">{onComplete?'YOUR YOGA CLASS':'COACH PREVIEW'}</span><h1>{flow.title}</h1><Tags flow={flow}/><p>{minutes(flowSeconds(flow))} · {flow.description}</p></div><button className="button secondary" onClick={onClose}>Back</button></div><div className="panel yoga-intention"><h3>{flow.theme}</h3><blockquote>“{flow.quote}”</blockquote><p className="muted">{flow.quoteAttribution}</p><p>{flow.openingIntention}</p></div><div className="panel yoga-session"><p className="eyebrow">{item.section} · Step {index+1} of {items.length}</p><progress aria-label="Class progress" value={index+elapsed/Math.max(total,1)} max={items.length}/><div className="yoga-session-grid"><div><PoseArt pose={pose}/><h2>{pose?.name??item.step.label}</h2><p className="muted">{pose?.sanskritName}</p><p>{pose?.instructions??item.step.cues}</p>{pose?.videoUrl?<a className="button secondary" href={pose.videoUrl} target="_blank" rel="noreferrer">Watch demonstration</a>:<p className="muted">Video to come.</p>}</div><div className="yoga-timer"><strong role="timer" aria-label="Remaining time">{duration(Math.max(0,total-elapsed))}</strong><p aria-live="polite">{phase.label}</p><p>{item.step.unit==='breaths'?`${item.step.hold} breaths per hold · ${item.step.secondsPerBreath}s per breath`:'Breathe naturally at your own pace.'}</p><button className="button primary" onClick={()=>{if(elapsed>=total)setElapsed(0);setPlaying(!playing);}}>{playing?'Pause':'Resume'}</button><div className="yoga-actions"><button className="button secondary" disabled={index===0} onClick={()=>go(index-1)}>Previous pose</button><button className="button secondary" disabled={index===items.length-1} onClick={()=>go(index+1)}>Next pose</button></div></div></div><div className="yoga-guidance-grid">{[['Breath guidance',pose?.breathInstructions],['Alignment',pose?.alignmentCues],['Common mistakes',pose?.commonMistakes],['Modifications',pose?.modifications],['Safety',pose?.contraindications],['Coaching cues',item.step.cues],['Transition',item.step.transitionNotes]].map(([title,text])=>text&&<div className="yoga-guidance" key={title}><h4>{title}</h4><p>{text}</p></div>)}</div></div><details className="panel yoga-outline"><summary>Class sections & ordered poses</summary>{flow.sections.map((s,i)=><div key={i}><h3>{i+1}. {s.title}</h3><ol>{s.steps.map((s,j)=><li key={j}>{poses.find(p=>p.id===s.poseId)?.name??s.label} · {s.side} · {s.hold} {s.unit} × {s.repetitions}</li>)}</ol></div>)}</details>{index===items.length-1&&<div className="panel yoga-intention"><h3>Closing reflection</h3><p>{flow.closingReflection}</p>{onComplete&&<button disabled={busy} className="button primary" onClick={complete}>{busy?'Saving…':'Complete class'}</button>}</div>}{error&&<p role="alert" className="form-error">{error}</p>}</div>;
}
