import { useState } from 'react';
import type { YogaPose } from '../yoga-types';
import Modal from './Modal';
import { categories, difficulties, PoseArt } from './YogaShared';
export default function YogaSelection({poses,onInsert,onClose}:{poses:YogaPose[];onInsert:(poses:YogaPose[])=>void;onClose:()=>void}) {
 const [search,setSearch]=useState(''),[category,setCategory]=useState(''),[difficulty,setDifficulty]=useState(''),[selected,setSelected]=useState<string[]>([]);
 const visible=poses.filter(p=>p.active&&[p.name,p.sanskritName,...p.aliases].join(' ').toLowerCase().includes(search.toLowerCase())&&(!category||p.category===category||p.position===category)&&(!difficulty||p.difficulty===difficulty));
 return <Modal title="Add poses to sequence" onClose={onClose} className="yoga-picker"><div className="yoga-filters"><input aria-label="Search poses to add" placeholder="English, Sanskrit or alias" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter poses" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All types</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select aria-label="Filter pose difficulty" value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="">All difficulties</option>{difficulties.map(c=><option key={c}>{c}</option>)}</select></div><p className="muted">Select in the order you want to teach. {selected.length} selected.</p><div className="yoga-selection-grid">{visible.map(p=><button className={`panel yoga-selection-card ${selected.includes(p.id)?'selected':''}`} key={p.id} aria-pressed={selected.includes(p.id)} onClick={()=>setSelected(selected.includes(p.id)?selected.filter(id=>id!==p.id):[...selected,p.id])}><PoseArt pose={p}/><strong>{p.name}</strong><small>{p.sanskritName}</small><span>{p.difficulty} · {p.category} · {p.recommendedHold}s</span>{selected.includes(p.id)&&<span className="badge sage">Selected #{selected.indexOf(p.id)+1}</span>}</button>)}</div><div className="modal-actions"><button className="button primary" disabled={!selected.length} onClick={()=>{onInsert(selected.map(id=>poses.find(p=>p.id===id)!));onClose();}}>Add to Sequence ({selected.length})</button></div></Modal>;
}
