import { useEffect, useState, type FormEvent } from 'react';
import { Activity, ArrowDownRight, ArrowRight, ArrowUpRight, Bell, CalendarDays, Check, CheckCircle2, ChevronRight, Dumbbell, Heart, LayoutDashboard, Leaf, LogOut, Menu, Plus, ShieldCheck, TrendingUp, Users, X } from 'lucide-react';
import { api, loadData } from './api';
import type { Data, Page, Role } from './types';
import PasswordRecovery from './components/PasswordRecovery';
import Library from './components/Library';
import Yoga from './components/Yoga';
import Workouts from './components/Workouts';
import Schedule from './components/Schedule';
import Progress from './components/Progress';
import Equipment from './components/Equipment';
import Clients from './components/Clients';
import Accounts from './components/Accounts';
import Modal from './components/Modal';
import Brand from './components/Brand';
import Registration, { registrationLink } from './components/Registration';
import '@fontsource/dm-sans/400.css';
import '@fontsource/dm-sans/500.css';
import '@fontsource/dm-sans/600.css';
import '@fontsource/dm-sans/700.css';

const nav = [{id:'overview',label:'Overview',icon:LayoutDashboard},{id:'clients',label:'My clients',icon:Users},{id:'workouts',label:'Workout plans',icon:Dumbbell},{id:'schedule',label:'Schedule',icon:CalendarDays},{id:'library',label:'Exercise library',icon:Activity},{id:'yoga',label:'Yoga',icon:Leaf},{id:'progress',label:'Progress & assessments',icon:TrendingUp},{id:'equipment',label:'Equipment',icon:Heart},{id:'accounts',label:'Manage coaches',icon:ShieldCheck}] as const;
const formatDate=(date:string)=>new Date(`${date}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'});
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};

export default function App(){
 const [authLink,setAuthLink]=useState(registrationLink);const [signingOut,setSigningOut]=useState(false);
 const [data,setData]=useState<Data|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const [page,setPage]=useState<Page>('overview');const [mobile,setMobile]=useState(false);const [toast,setToast]=useState('');const [notice,setNotice]=useState(false);const [accountOpen,setAccountOpen]=useState(false);
 const refresh=async()=>{setData(await loadData());};
 useEffect(()=>{const changed=()=>setAuthLink(registrationLink());window.addEventListener('hashchange',changed);return()=>window.removeEventListener('hashchange',changed);},[]);
 useEffect(()=>{loadData().then(setData).catch(e=>{if(!String(e.message).toLowerCase().match(/sign|auth|log|session/))setError(e.message);}).finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(timer);}},[toast]);
 const navigate=(p:Page)=>{setPage(p);setMobile(false);window.scrollTo({top:0,behavior:'smooth'});};
 const clearAuthLink=()=>{window.history.replaceState(null,'',window.location.pathname+window.location.search);setAuthLink(null);};
 async function logout(){setSigningOut(true);try{await api('/auth/logout','POST');setData(null);setPage('overview');setNotice(false);setAccountOpen(false);setMobile(false);setToast('');setError('');clearAuthLink();}catch(e){setToast((e as Error).message);}finally{setSigningOut(false);}}
 if(loading)return <div className="loading-screen"><Brand/><span className="loading-ring"/><p>Getting your workspace ready…</p></div>;
 if(authLink?.kind==='reset')return <PasswordRecovery token={authLink.token} onBack={()=>{setData(null);clearAuthLink();}}/>;
 if(authLink)return <Registration link={authLink} onCancel={clearAuthLink} onComplete={async()=>{await refresh();clearAuthLink();setPage('overview');setMobile(false);}}/>;
 if(!data)return <Login onLogin={async()=>{await refresh();setPage('overview');}} initialError={error}/>;
 const client=data.user.role==='client'; const shared={data,refresh,notify:setToast};
 const pages = nav.filter(n=>(!client||!['clients','library'].includes(n.id))&&(n.id!=='accounts'||data.user.role==='admin'));
 return <div className="app-shell"><aside className={`sidebar ${mobile?'is-open':''}`}><div className="sidebar-brand"><Brand/><button className="icon-button mobile-close" aria-label="Close menu" onClick={()=>setMobile(false)}><X size={20}/></button></div><div className="workspace-badge"><span className="workspace-dot"/>{client?'Your training space':data.user.role==='admin'?'Admin workspace':'Coach workspace'}</div><div className="nav-label">WORKSPACE</div><nav aria-label="Main navigation">{pages.map(n=><button key={n.id} className={`nav-item ${page===n.id?'active':''}`} onClick={()=>navigate(n.id)}><n.icon size={19}/><span>{client&&n.id==='workouts'?'My workouts':client&&n.id==='yoga'?'My yoga':n.label}</span>{n.id==='clients'&&<span className="nav-count">{data.clients.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-quote"><Leaf size={22}/><p>Good coaching.<br/><strong>Lasting change.</strong></p><span>One session at a time.</span></div><div className="account"><div className="avatar">{data.user.name.split(' ').map(n=>n[0]).join('').slice(0,2)}</div><button className="account-details" onClick={()=>{setMobile(false);setAccountOpen(true);}} title="Account settings"><strong>{data.user.name}</strong><span>{data.user.role==='admin'?'Administrator':client?'Client':'Personal trainer'}</span></button></div>{client&&<button className="button secondary account-reset-button" onClick={()=>{setMobile(false);setAccountOpen(true);}}>Reset password</button>}</div></aside>{mobile&&<div className="sidebar-overlay" onClick={()=>setMobile(false)}/>}
 <div className="main-wrap"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" onClick={()=>setMobile(true)} aria-label="Open menu"><Menu size={20}/></button><span>Workspace</span><ChevronRight size={14}/><strong>{nav.find(n=>n.id===page)?.label}</strong></div><div className="topbar-right"><button className="button secondary sign-out-button" onClick={logout} disabled={signingOut}><LogOut size={16}/><span>{signingOut?'Signing out…':'Sign out'}</span></button><span className="topbar-date">{new Date().toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}</span>{data.demoMode&&<span className="demo-label">Demo workspace</span>}<button className="notification-button icon-button" aria-label="View updates" onClick={()=>setNotice(true)}><Bell size={19}/><i/></button></div></header><main className="main-content">{page==='overview'?<Overview data={data} navigate={navigate}/>:page==='library'?(!client?<Library {...shared}/>:<div className="panel empty-state">Coach access required.</div>):page==='yoga'?<Yoga key={data.user.id} data={data} notify={setToast}/>:page==='workouts'?<Workouts {...shared}/>:page==='schedule'?<Schedule {...shared}/>:page==='progress'?<Progress {...shared}/>:page==='equipment'?<Equipment {...shared}/>:page==='accounts'?<Accounts {...shared}/>:<Clients {...shared} navigate={navigate}/>}<footer className="workspace-footer"><Brand small/><span>Made for progress. Built around people.</span><span>{data.demoMode?'Sample data · ':''}{data.user.role} access</span></footer></main></div>
 {toast&&<div className="toast" role="status"><CheckCircle2 size={19}/><span>{toast}</span><button className="icon-button" aria-label="Dismiss message" onClick={()=>setToast('')}><X size={15}/></button></div>}
 {accountOpen&&<AccountSettings client={client} onClose={()=>setAccountOpen(false)} notify={setToast}/>}
 {notice&&<Modal title="Your workspace updates" onClose={()=>setNotice(false)}><div className="updates-list"><p className="muted">A quick look at what’s happening.</p><div><CheckCircle2 size={22}/><span><strong>{data.logs.length} workouts completed</strong><small>Every session is a step forward. Review details in Progress.</small></span></div><div><CalendarDays size={22}/><span><strong>{data.sessions.filter(s=>s.date>=localDate()).length} upcoming sessions</strong><small>Open your schedule to view the details.</small></span></div><button className="button primary" onClick={()=>{setNotice(false);navigate('progress');}}>View progress<ArrowRight size={16}/></button></div></Modal>}
 </div>;
}

function AccountSettings({onClose,notify,client}:{onClose:()=>void;notify:(m:string)=>void;client:boolean}){
 const [forgot,setForgot]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const values=new FormData(e.currentTarget);if(values.get('password')!==values.get('confirm')){setError('Your new passwords don’t match.');return;}setSaving(true);setError('');try{await api('/auth/password','POST',{currentPassword:values.get('current'),newPassword:values.get('password')});notify('Password changed. Other sessions have been signed out.');onClose();}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 return <Modal title={client?"Reset your password":"Account settings"} onClose={()=>{if(!saving)onClose();}}><p className="modal-intro">Choose a strong password to keep your training workspace private.</p><button type="button" className="text-button" onClick={()=>setForgot(!forgot)}>Forgot your current password?</button>{forgot&&<p role="status" className="modal-intro">Ask your coach or administrator for a private password reset link. Open that link to choose a new password without your current password. The link expires after 30 minutes. Email recovery will be available after the email service is configured.</p>}<form onSubmit={save}><div className="account-password-fields"><label className="field">Current password<input required type="password" name="current" autoComplete="current-password"/></label><label className="field">New password<input required type="password" name="password" minLength={8} autoComplete="new-password"/><small>At least 8 characters.</small></label><label className="field">Confirm new password<input required type="password" name="confirm" minLength={8} autoComplete="new-password"/></label></div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" disabled={saving} onClick={onClose}>Cancel</button><button className="button primary" disabled={saving}>{saving?'Saving…':'Change password'}</button></div></form></Modal>;
}

function Login({onLogin,initialError}:{onLogin:()=>Promise<void>;initialError:string}){
 const [recover,setRecover]=useState(false);
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState(initialError);const [busy,setBusy]=useState(false);const [demoRole,setDemoRole]=useState<Role|null>(null);const [demoMode,setDemoMode]=useState(false);
 useEffect(()=>{api<{demoMode:boolean}>('/config').then(c=>setDemoMode(c.demoMode)).catch(()=>{});},[]);
 async function login(e?:FormEvent,role?:Role){e?.preventDefault();setBusy(true);setError('');setDemoRole(role||null);try{await api('/auth/login','POST',role?{email:role==='client'?'jamie@form.fit':`${role}@form.fit`,password:'FormDemo123!'}:{email,password});await onLogin();}catch(e){setError((e as Error).message);}finally{setBusy(false);setDemoRole(null);}}
 if(recover)return <PasswordRecovery onBack={()=>setRecover(false)}/>;
 return <div className="login-layout"><section className="login-story"><Brand/><div className="login-story-copy"><span className="eyebrow">PERSONAL TRAINING, CONNECTED.</span><h1>Big goals.<br/>Small steps.<br/><em>Real progress.</em></h1><p>A thoughtful home for your coaching, your clients, and every little win along the way.</p><div className="login-feature"><Check size={17}/>Plan with purpose</div><div className="login-feature"><Check size={17}/>Coach with confidence</div><div className="login-feature"><Check size={17}/>See the progress together</div></div><div className="login-art"><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><Dumbbell size={112} strokeWidth={1}/></div><span className="login-story-footer">BUILT AROUND PEOPLE. MADE FOR PROGRESS.</span></section><section className="login-form-wrap"><div className="login-form-card"><span className="eyebrow">YOUR NEXT CHAPTER</span><h2>Welcome to Train with me.</h2><p className="login-subtitle">A little structure. A lot of possibility.</p><form onSubmit={e=>login(e)}><label className="field">Email address<input type="email" autoComplete="username" required placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field">Password<input type="password" autoComplete="current-password" required placeholder="Your password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="button primary login-submit" disabled={busy}>{busy&&!demoRole?'Signing in…':'Sign in'}<ArrowRight size={17}/></button></form><button type="button" className="text-button" onClick={()=>setRecover(true)}>Forgot password?</button>{error&&<div role="alert" className="form-error">{error}</div>}{demoMode&&<><div className="login-divider"><span>Explore the demo</span></div><p className="demo-description">Sample accounts. Real workflows. Pick your perspective.</p><div className="demo-accounts">{([{role:'coach',name:'Coach',text:'Plan & guide',icon:Users},{role:'admin',name:'Admin',text:'Curate the library',icon:ShieldCheck},{role:'client',name:'Client',text:'Train & track',icon:Dumbbell}] as const).map(d=><button key={d.role} disabled={busy} onClick={()=>login(undefined,d.role)}><d.icon size={21}/><strong>{demoRole===d.role?'Opening…':d.name}</strong><span>{d.text}</span></button>)}</div></>}<p className="client-registration-help">New client? Open the signup link from your coach to create your account.</p><p className="login-note"><ShieldCheck size={14}/>Role-based access · Data saved to this workspace</p></div></section></div>;
}

function Overview({data,navigate}:{data:Data;navigate:(p:Page)=>void}){
 const client=data.user.role==='client';const today=localDate(); const currentClient=data.clients[0];
 const monday=new Date(`${today}T12:00:00`);monday.setDate(monday.getDate()-((monday.getDay()+6)%7));const start=monday.toISOString().slice(0,10);const end=new Date(monday);end.setDate(end.getDate()+6);const finish=end.toISOString().slice(0,10);
 const weekly=data.plans.filter(p=>p.date>=start&&p.date<=finish);const weeklyDone=weekly.filter(p=>data.logs.some(l=>l.planId===p.id));const rate=weekly.length?Math.round(weeklyDone.length/weekly.length*100):0;
 const upcoming=[...data.sessions].filter(s=>s.date>=today).sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)).slice(0,3);
 const recent=[...data.logs].sort((a,b)=>`${b.date}${b.id}`.localeCompare(`${a.date}${a.id}`)).slice(0,3);
 const firstName=data.user.name.split(' ')[0];
 const cards=client?[{label:'This week’s workouts',value:weekly.length,detail:'Your plan, one session at a time',icon:Dumbbell,color:'sage',link:'workouts'},{label:'Workouts completed',value:data.logs.length,detail:'Consistency looks good on you',icon:CheckCircle2,color:'peach',link:'progress'},{label:'Weekly completion',value:`${rate}%`,detail:`${weeklyDone.length} of ${weekly.length} workouts this week`,icon:TrendingUp,color:'lavender',link:'workouts'},{label:'Upcoming sessions',value:upcoming.length,detail:'Your next chance to show up',icon:CalendarDays,color:'sand',link:'schedule'}]:[{label:'Active clients',value:data.clients.length,detail:'Good things happen together',icon:Users,color:'sage',link:'clients'},{label:'Weekly completion',value:`${rate}%`,detail:`${weeklyDone.length} of ${weekly.length} workouts completed`,icon:CheckCircle2,color:'peach',link:'workouts'},{label:'Workouts this week',value:weekly.length,detail:'Every plan has a purpose',icon:Dumbbell,color:'lavender',link:'workouts'},{label:'Upcoming sessions',value:data.sessions.filter(s=>s.date>=today).length,detail:'A little time. A lasting impact.',icon:CalendarDays,color:'sand',link:'schedule'}];
 return <><div className="page-heading overview-heading"><div><span className="eyebrow">LET’S MAKE TODAY COUNT</span><h1>Good {new Date().getHours()<12?'morning':new Date().getHours()<17?'afternoon':'evening'}, {firstName}<span className="heading-dot">.</span></h1><p>{client?'Your goals are getting closer. Keep showing up.':'Here’s how your people are moving forward.'}</p></div><button className="button primary" onClick={()=>navigate('workouts')}>{client?<Dumbbell size={17}/>:<Plus size={17}/>} {client?'View my workouts':'Build a workout'}</button></div>
 <section className="hero-banner"><div className="hero-copy"><span className="hero-kicker"><span/>THE POWER OF SHOWING UP</span><h2>A little progress,<br/><em>every day.</em></h2><p>{client?'Your next workout is a fresh opportunity. Let’s take the next step.':'Behind every milestone is a coach who cares. Keep making a difference.'}</p><button onClick={()=>navigate(client?'workouts':'clients')}>{client?'Find your next workout':'Check in with your clients'}<ArrowUpRight size={17}/></button></div><div className="hero-art" aria-hidden="true"><span className="hero-orbit one"/><span className="hero-orbit two"/><span className="hero-orbit three"/><div className="hero-dumbbell"><Dumbbell size={142} strokeWidth={1.2}/></div><div className="hero-floating-tag"><span className="mini-leaf"><Leaf size={15}/></span>Grow at your own pace.</div><span className="hero-star">✳</span><span className="hero-small-star">✳</span></div></section>
 <div className="stat-grid">{cards.map(s=><button key={s.label} className="stat-card" onClick={()=>navigate(s.link as Page)}><div className="stat-top"><span className={`stat-icon ${s.color}`}><s.icon size={19}/></span><ArrowUpRight size={15} className="muted"/></div><span className="stat-label">{s.label}</span><strong className="stat-value">{s.value}</strong><span className="stat-detail">{s.detail}</span></button>)}</div>
 <div className="dashboard-columns"><section className="panel dashboard-panel"><div className="panel-heading"><div><h2>{client?'Your next sessions':'Coming up next'}</h2><p>A little planning goes a long way.</p></div><button className="text-button" onClick={()=>navigate('schedule')}>View schedule<ArrowUpRight size={15}/></button></div><div className="upcoming-list">{upcoming.length?upcoming.map(s=>{const c=data.clients.find(c=>c.id===s.clientId);return <div className="upcoming-row" key={s.id}><div className="calendar-tile"><span>{new Date(`${s.date}T12:00:00`).toLocaleDateString('en-US',{month:'short'}).toUpperCase()}</span><strong>{s.date.slice(-2)}</strong></div><div className="session-summary"><strong>{client?`${s.type} training`:c?.name}</strong><span>{s.time} · {s.duration} min <span className="tiny-dot">·</span> {s.type}</span></div><span className={`badge ${s.type==='Online'?'lavender':'sage'}`}>{s.type==='Online'?'Online':'In person'}</span></div>}):<div className="empty-state compact"><CalendarDays size={26}/><p>No upcoming sessions.</p><button className="text-button" onClick={()=>navigate('schedule')}>{client?'View schedule':'Schedule a session'}<ArrowRight size={14}/></button></div>}</div><div className="panel-bottom-note"><span className="status-dot"/>{upcoming.length?'A good week starts with a plan.':'Make room for the next step.'}</div></section>
 <section className="panel dashboard-panel"><div className="panel-heading"><div><h2>Little wins, big momentum</h2><p>{client?'Look how far you’ve come.':'Your clients have been putting in the work.'}</p></div><button className="text-button" onClick={()=>navigate('progress')}>View progress<ArrowUpRight size={15}/></button></div><div className="activity-list">{recent.length?recent.map(l=>{const c=data.clients.find(c=>c.id===l.clientId);const p=data.plans.find(p=>p.id===l.planId);return <div className="activity-row" key={l.id}><div className="avatar" style={{background:c?.color}}>{c?.name.split(' ').map(n=>n[0]).join('').slice(0,2)}</div><div><p><strong>{client?'You':c?.name}</strong> completed a workout</p><span>{p?.name||'Training session'} · {formatDate(l.date)}</span></div><CheckCircle2 size={19} className="success-icon"/></div>}):<div className="empty-state compact"><TrendingUp size={26}/><p>The first win is just ahead.</p><span>Completed workouts will appear here.</span></div>}</div><div className="panel-bottom-note"><Heart size={14}/>{client?'Consistency is your superpower.':'Celebrate the effort, not just the outcome.'}</div></section></div>
 <section className="week-panel panel"><div className="panel-heading"><div><h2>Your week at a glance</h2><p>{formatDate(start)} – {formatDate(finish)} · {client?'Find your rhythm.':'A little structure for a stronger week.'}</p></div><button className="text-button" onClick={()=>navigate('workouts')}>View workout plans<ArrowUpRight size={15}/></button></div><div className="week-strip">{Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(d.getDate()+i);const day=d.toISOString().slice(0,10);const plans=weekly.filter(p=>p.date===day);return <button className={`week-day ${day===today?'today':''}`} key={i} onClick={()=>navigate('workouts')}><span>{d.toLocaleDateString('en-US',{weekday:'short'})}</span><strong>{d.getDate()}</strong><div className="day-dots">{plans.slice(0,4).map(p=><i key={p.id} className={data.logs.some(l=>l.planId===p.id)?'complete':''}/>)}</div><small>{plans.length?`${plans.length} workout${plans.length>1?'s':''}`:'Recovery day'}</small></button>})}</div></section>
 <div className="overview-note"><Leaf size={18}/><p>{client?`${currentClient?.goal||'Build strength. Find balance. Keep going.'}`:'Coaching is more than a plan. It’s a partnership.'}</p><span>YOU’VE GOT THIS.</span></div>
 </>;
}
